name: MLflow CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Start job"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create env from conda.yaml
        shell: bash -l {0}
        run: |
          conda env create -f MLProject/conda.yaml -n mlflow-env
          conda activate mlflow-env
          conda info

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install mlflow==2.9.2

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run . \
            -P n_estimators=100 \
            -P max_depth=10 \
            -P dataset=day_wise_processed.csv

      - name: Check outputs
        shell: bash -l {0}
        run: |
          ls -la MLProject
          ls -la MLProject/mlruns || true
          ls -la MLProject/model || true
          find MLProject/model -name "MLmodel" || true

      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: MLProject/mlruns/

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: MLProject/model/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Model
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow models build-docker \
            -m model \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ github.sha }}

      - name: Complete job
        run: echo "Complete"
