name: MLflow CI Advanced

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Start job"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          miniconda-version: "latest"

      - name: Create env from conda.yaml
        shell: bash -l {0}
        run: |
          conda env create -f MLProject/conda.yaml -n mlflow-env
          conda run -n mlflow-env python --version
          conda run -n mlflow-env mlflow --version
          conda run -n mlflow-env which mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          conda run -n mlflow-env mlflow run . --experiment-name CI-Retraining-Experiment \
            -P n_estimators=100 \
            -P max_depth=10 \
            -P dataset=day_wise_processed.csv

      - name: Check outputs
        shell: bash -l {0}
        run: |
          ls -la MLProject
          ls -la MLProject/mlruns || true
          ls -la MLProject/model || true
          find MLProject/model -name "MLmodel" || true

      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: MLProject/mlruns/

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: MLProject/model/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fix Docker Host
        run: |
          echo "DOCKER_HOST=$DOCKER_HOST"
          unset DOCKER_HOST
          docker version
          docker info

      - name: Build Docker Model
        shell: bash -l {0}
        run: |
          unset DOCKER_HOST
          cd MLProject
          conda run -n mlflow-env mlflow models build-docker \
            -m model \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ github.sha }}

      - name: Complete job
        run: echo "Complete"
